# Generated by Django 2.1.1 on 2018-09-24 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('encrypted_password', models.TextField()),
                ('organization', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryKey',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='logins_temporary_key', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('encrypted_password', models.TextField()),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='password',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins_encrypted', to=settings.AUTH_USER_MODEL),
        ),
    ]
